version: "3"
services:
  springboot-app:
    depends_on:
        - mysqldb
    image: application-image
    restart: always
    build: .
    ports:
      - 8888:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - C:\Users\Dell\Desktop\db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: employeemanager
      MYSQL_ROOT_PASSWORD: root